apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: concept
        valueFrom:
          configMapKeyRef:
            name: nginx-config # name of the configmap you are referring to
            key: concept # env.name and configmap can be different
      - name: cloud
        valueFrom:
          configMapKeyRef:
            name: nginx-config
            key: cloud